<Project>
  <ItemGroup>
    <PackageVersion Include="NSwag.CodeGeneration.CSharp" Version="14.4.0" />
    <PackageVersion Include="coverlet.collector" Version="6.0.4" />
    <PackageVersion Include="Microsoft.NET.Test.Sdk" Version="17.8.0" />
    <PackageVersion Include="xunit" Version="2.9.3" />
    <PackageVersion Include="xunit.runner.visualstudio" Version="3.1.0" />
    <PackageVersion Include="Microsoft.AspNetCore.Mvc.Testing" Version="8.0.0" />
    <PackageVersion Include="Bogus" Version="35.6.3" />
    <PackageVersion Include="FluentAssertions" Version="7.2.0" />
    <PackageVersion Include="SpecFlow" Version="3.9.74" />
    <PackageVersion Include="SpecFlow.xUnit" Version="3.9.74" />
    <PackageVersion Include="SpecFlow.Tools.MsBuild.Generation" Version="3.9.74" />
    
    <PackageVersion Include="Microsoft.EntityFrameworkCore.Design" Version="8.0.16" />
    <PackageVersion Include="Microsoft.EntityFrameworkCore" Version="8.0.16" />
    <PackageVersion Include="Microsoft.EntityFrameworkCore.Relational" Version="8.0.16.0" />
    <PackageVersion Include="Microsoft.VisualStudio.Azure.Containers.Tools.Targets" Version="1.21.0" />
    <PackageVersion Include="Newtonsoft.Json" Version="13.0.3" />
    <PackageVersion Include="Npgsql.EntityFrameworkCore.PostgreSQL" Version="8.0.11" />
    <PackageVersion Include="Swashbuckle.AspNetCore" Version="6.6.2" />
    
    <PackageVersion Include="SonarAnalyzer.CSharp" Version="10.10.0.116381" />
    <PackageVersion Include="StyleCop.Analyzers" Version="1.1.118" />
    
    <PackageVersion Include="Serilog" Version="4.2.0" />
    <PackageVersion Include="Serilog.Extensions.Hosting" Version="8.0.0" />
    <PackageVersion Include="Serilog.Settings.Configuration" Version="8.0.0" />
    <PackageVersion Include="Serilog.Sinks.Console" Version="6.0.0" />
  </ItemGroup>
</Project>